language: node_js
node_js:
- node
deploy:
  provider: npm
  email: Nils_Hirsekorn@online.de
  api_key:
    secure: TpPJkTAxANup2Mn27dV7ooHbdEGKKKPhq8ggpjCP76ITrg4zBVkeSZuNSal51msEFH3V1+unat0tkewRpOyaIHELWJJhpV3rK1ejw4Z4S50riwwKyBW2X8ePEkg0IcYYl7K/5uJmBXXDA4KtVYldpF3dlJRPSm7XkHwKfEBPg48xdC4XndBh5NV7hRewR0fGjp59jzg2mu56HMYZTSCq2BbxXNm0YB9uoFpkHcvLZvWMikWab0Y2AjPXRg4VzZ3Ukp9v1s7Cd4on060aTC59DJBRkiig3OLpQZjIHOPnlPyjPzP0EZfKs6/sTon2nRpnSx3zayyTv4S8yVzxL/KC/S3EaTp5Ea6f/R+PlPNOld0FYEPo2/lcQINSQhSBpfYCpDj3im/9HPvbTB59gd9mmaIi+z++lrlh20lZNL4CEB7kHYqUbJ6REvstC+pAFR4cpte0WN7nVSS5sv8K9p7hN8DWn74OjX1W2lbScJvMQ1IauASsJXd40vvttWRsKpofKs0rBc3RA2MsOdwODrOIiJIIzhzGc9eac37d5Y6wQ4uniYaLRVk/oM475p1Tm59UOs+A7ODRihInjr9C5rG9zcya+ldIya9AmNd3x9esKJhiwvcDNwduBPXmgdJYnPFWV7R1AXIbAwU0YpUvk4DQy36G45UG1Je5zQZZOmr+ppI=
  on:
    tags: true
    repo: Kkoile/figure-speaker-wifi-connector
