language: node_js
node_js:
- node
deploy:
  provider: npm
  email: Nils_Hirsekorn@online.de
  api_key:
    secure: aoE9TZU5L7qDn/XxB4DTTCh8PjlRm431+F4WxSdWk70KXix+mDCGokeErMUKLe2pWoesiyoMiOFzEf6lSc+uLFHwG+4LFcss2oHE1r1EHdHS3jCQ1bf7LbC+vzhwr+haQtAcXMls8qtKsWz8AJ91WtqwHye+PL9JB+qfNgASjZ/ob4NvK18XurRBPP2cqfTMyWDXtqhlSBg4Xww+ld9T7Vm6JD4fNBRjLQdm8QWznwPMfbmaKT6tRAmYFllIwNsYcCmdE40na3MiVooL8xQ4ONyn9e6oRqV0zeeqo7no0jyOjcJN7h/Ox/aG+dpTfs66T7zukHerMDomGAVdA4FwXLDZHOQX36rUsuZPIxEIWBAI/QecwiIlN8kLIL/rWnG8t3dMwAwrWy/uYC5FM8x695lBDCZnVjqVZB7MuTTPeOZa5Khe+g6uwb7q4WahRN2hBhbA/H2YzfIHpfwLI8W/Fc6aYPlDL198lMjUwem3N8sHuzU6KnRDGPKz4G11TFd5dsK9GXLuuJC4j6H98LtNZCVtCOR2eJf5K5V4PJ83AAtl5rcrPBcz/VMcbIiFl8nO3NOf1L9KiqhpoG2MbrV8OjZIpEZ2Zavly2PUYwD/s5eaN1Rd3CZn1gI5aXc0x1x74P02+7IQHSDnHzGM+c8hEmozWmz79TsmlhNDlIK7C9w=
  on:
    tags: true
    repo: Kkoile/figure-speaker-wifi-connector
